/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 15-kv�-2016 12:42:36 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Drop Tables */

DROP TABLE IF EXISTS `Zamestnanec` CASCADE
;

DROP TABLE IF EXISTS `Login` CASCADE
;

DROP TABLE IF EXISTS `Pracovni_den` CASCADE
;

DROP TABLE IF EXISTS `Absencni_den` CASCADE
;

DROP TABLE IF EXISTS `Objednavka` CASCADE
;

/* Create Tables */

CREATE TABLE `Zamestnanec`
(
	`ID_Zam` INT NOT NULL AUTO_INCREMENT,
	`Jmeno` VARCHAR(50) 	 NULL,
	`Prijmeni` VARCHAR(50) 	 NULL,
	`Sazba` INT 	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`ID_Zam`)
)

;

CREATE TABLE `Login`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(50) 	 NULL,
	`password` VARCHAR(255) 	 NULL,
  	`role` VARCHAR(50)  NULL,
  	`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	`updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  	`remember_token` int(11) NOT NULL,
	`ID_Zam` INT 	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id`)
)

;

CREATE TABLE `Pracovni_den`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`Datum` DATE NOT NULL,
	`Hodiny` INT 	 NULL,
	`ID_Zam` INT 	 NULL,
	`ID_Obj` INT	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id`)
)

;

CREATE TABLE `Absencni_den`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`Datum` DATE NOT NULL,
	`ID_Zam` INT 	 NULL,
	`Hodiny` INT 	 NULL,
	`Duvod` VARCHAR(200) 	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id`)
)

;

CREATE TABLE `Objednavka`
(
	`id` INT NOT NULL,
	`Jmeno` VARCHAR(50) 	 NULL,
	`Od` DATE 	 NULL,
	`Do` DATE 	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id`)
)

;

/* Create Indexes, Uniques, Checks */

ALTER TABLE `Login` 
 ADD INDEX `IXFK_Login_Zamestnanec` (`ID_Zam` ASC)
;

ALTER TABLE `Pracovni_den` 
 ADD INDEX `IXFK_Pracovni_den_Zamestnanec` (`ID_Zam` ASC)
;

ALTER TABLE `Pracovni_den` 
 ADD INDEX `IXFK_Pracovni_den_Objednavka` (`id` ASC)
;

ALTER TABLE `Absencni_den` 
 ADD INDEX `IXFK_Absencni_den_Zamestnanec` (`ID_Zam` ASC)
;


/* Create Foreign Key Constraints */

ALTER TABLE `Login` 
 ADD CONSTRAINT `FK_Login_Zamestnanec`
	FOREIGN KEY (`ID_Zam`) REFERENCES `Zamestnanec` (`ID_Zam`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Pracovni_den` 
 ADD CONSTRAINT `FK_Pracovni_den_Zamestnanec`
	FOREIGN KEY (`ID_Zam`) REFERENCES `Zamestnanec` (`ID_Zam`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Pracovni_den` 
 ADD CONSTRAINT `FK_Pracovni_den_Objednavka`
	FOREIGN KEY (`ID_Obj`) REFERENCES `Objednavka` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Absencni_den` 
 ADD CONSTRAINT `FK_Absencni_den_Zamestnanec`
	FOREIGN KEY (`ID_Zam`) REFERENCES `Zamestnanec` (`ID_Zam`) ON DELETE Restrict ON UPDATE Restrict
;


SET FOREIGN_KEY_CHECKS=1 ;
