/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 15-kvì-2016 12:42:36 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Drop Tables */

DROP TABLE IF EXISTS `Zamestnanec` CASCADE
;

DROP TABLE IF EXISTS `Login` CASCADE
;

DROP TABLE IF EXISTS `Pracovni_den` CASCADE
;

DROP TABLE IF EXISTS `Absencni_den` CASCADE
;

DROP TABLE IF EXISTS `Objednavka` CASCADE
;

/* Create Tables */

CREATE TABLE `Zamestnanec`
(
	`ID_Zam` INT NOT NULL,
	`Jmeno` VARCHAR(50) 	 NULL,
	`Prijmeni` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`ID_Zam`)
)

;

CREATE TABLE `Login`
(
	`ID_Login` INT NOT NULL,
	`Username` VARCHAR(50) 	 NULL,
	`Password` VARCHAR(50) 	 NULL,
  `Role` VARCHAR(50)  NULL,
	`ID_Zam` INT 	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`ID_Login`)
)

;

CREATE TABLE `Pracovni_den`
(
	`Datum` DATE NOT NULL,
	`Cislo_VP` INT 	 NULL,
	`Hodiny` INT 	 NULL,
	`ID_Zam` INT 	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`Datum`)
)

;

CREATE TABLE `Absencni_den`
(
	`Datum` DATE NOT NULL,
	`ID_Zam` INT 	 NULL,
	`Hodiny` INT 	 NULL,
	`Duvod` VARCHAR(200) 	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`Datum`)
)

;

CREATE TABLE `Objednavka`
(
	`Cislo_VP` INT NOT NULL,
	`Jmeno` VARCHAR(50) 	 NULL,
	`Od` DATE 	 NULL,
	`Do` DATE 	 NULL,
	`Sazba` INT 	 NULL,
	`Datum` DATE 	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`Cislo_VP`)
)

;

/* Create Indexes, Uniques, Checks */

ALTER TABLE `Login` 
 ADD INDEX `IXFK_Login_Zamestnanec` (`ID_Zam` ASC)
;

ALTER TABLE `Pracovni_den` 
 ADD INDEX `IXFK_Pracovni_den_Zamestnanec` (`ID_Zam` ASC)
;

ALTER TABLE `Absencni_den` 
 ADD INDEX `IXFK_Absencni_den_Zamestnanec` (`ID_Zam` ASC)
;

ALTER TABLE `Objednavka` 
 ADD INDEX `IXFK_Objednavka_Pracovni_den` (`Datum` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `Login` 
 ADD CONSTRAINT `FK_Login_Zamestnanec`
	FOREIGN KEY (`ID_Zam`) REFERENCES `Zamestnanec` (`ID_Zam`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Pracovni_den` 
 ADD CONSTRAINT `FK_Pracovni_den_Zamestnanec`
	FOREIGN KEY (`ID_Zam`) REFERENCES `Zamestnanec` (`ID_Zam`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Absencni_den` 
 ADD CONSTRAINT `FK_Absencni_den_Zamestnanec`
	FOREIGN KEY (`ID_Zam`) REFERENCES `Zamestnanec` (`ID_Zam`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Objednavka` 
 ADD CONSTRAINT `FK_Objednavka_Pracovni_den`
	FOREIGN KEY (`Datum`) REFERENCES `Pracovni_den` (`Datum`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 ;
